### ISSUE TITLE
Fails if tidy-html5 is already installed

### ISSUE THREAD

**Issue by eserte** [robrwo/Alien-TidyHTML5#2]
The test suite fails on my FreeBSD smokers, see http://matrix.cpantesters.org/?dist=Alien-TidyHTML5%20v0.1.1;os=freebsd;reports=1

But it seems to pass if I deinstall the tidy-html5 package.

**Comment by robrwo** [comment]
Could this be related to #1?

**Comment by eserte** [comment]
Don't know. If it helps, here's the list of files installed by the package:
```
tidy-html5-5.6.0:
        /usr/local/bin/tidy5
        /usr/local/include/tidy.h
        /usr/local/include/tidybuffio.h
        /usr/local/include/tidyenum.h
        /usr/local/include/tidyplatform.h
        /usr/local/lib/libtidy.so.5
        /usr/local/lib/libtidy.so.5.6.0
        /usr/local/lib/libtidy5.so
        /usr/local/lib/libtidys.a
        /usr/local/libdata/pkgconfig/tidy.pc
        /usr/local/man/man1/tidy5.1.gz
        /usr/local/share/licenses/tidy-html5-5.6.0/LICENSE
        /usr/local/share/licenses/tidy-html5-5.6.0/MIT
        /usr/local/share/licenses/tidy-html5-5.6.0/catalog.mk
```

**Comment by robrwo** [comment]
The problem seems to be the run_ok method in Test::Alien https://metacpan.org/pod/Test::Alien#run_ok

**Comment by robrwo** [comment]
@eserte Is the package named "tidy5"? (See #1)

**Comment by eserte** [comment]
The package name is "tidy-html5":
```
$ pkg info tidy-html5-5.6.0
tidy-html5-5.6.0
Name           : tidy-html5
Version        : 5.6.0
...
```

**Comment by eserte** [comment]
Well, that's the *freebsd* package name. The *pkgconf* name is `tidy` (see above, `/usr/local/libdata/pkgconfig/tidy.pc` is installed)

**Comment by robrwo** [comment]
Hm. The `alienfile` has it looking for a package named "tidy". Perhaps that's the issue? Can you manually run tests by changing the package name in `alienfile` and letting me know if it works?

**Comment by eserte** [comment]
Well, if the package name is changed (e.g. to `tidy5`), then the already installed package is not found anymore via pkgconf and things indeed pass. But this is probably not the right solution.

Also it passes if I apply this diff:
```
diff --git a/t/01-tidy.t b/t/01-tidy.t
index 5b33645..38cc4fa 100644
--- a/t/01-tidy.t
+++ b/t/01-tidy.t
@@ -3,7 +3,7 @@ use Test::Alien;
 use Alien::TidyHTML5;
 
 alien_ok 'Alien::TidyHTML5';
-run_ok( [qw/ tidy -version /] )
+run_ok( [qw/ tidy5 -version /] )
     ->success
     ->out_like(qr/^HTML Tidy /);
 
```

But this is also not the right fix, as it would start to fail on other OS.

Maybe Alien::TidyHTML5 should know how the executable is named and provide a function to return either `/usr/bin/tidy` or `/usr/local/bin/tidy5` or so?

**Comment by robrwo** [comment]
I've just pushed some code to the repo that may fix this issue. Can you test it to see if that fixes it?

**Comment by eserte** [comment]
`/usr/perl5.24.2p/bin/dzil test` on a freebsd 10 system is successful (checked out commit is 907d2ba0698977f919b5b27d56019cb8c45623a9 ). Though it seems that the installed package is ignored now and tidy is downloaded and built from scratch.

**Comment by robrwo** [comment]
@eserte Can you try it with commit 8b89d44a0d52283201dabfba601c0d48fa2a2bd1 reverted, and see if that passes but does not download a new version?

**Comment by eserte** [comment]
With this commit reverted (and the conflict in the Changes file resolved) it does not pass (and it seems that there's no download):
```
t/01-tidy.t .................. 1/?
# Failed test 'exe_file'
# at t/01-tidy.t line 7.
Use of uninitialized value $command[0] in join or string at /usr/perl5.24.2p/lib/site_perl/5.24.2/Test/Alien.pm line 81.

# Failed test 'run  -version'
# at t/01-tidy.t line 9.
#   command not found

# Failed test 'command succeeded'
# at t/01-tidy.t line 9.
#   command not found

# Failed test 'output matches (?^:^HTML Tidy )'
# at /usr/perl5.24.2p/lib/site_perl/5.24.2/Test/Alien/Run.pm line 92.
#   out:
#   does not match:
#     (?^:^HTML Tidy )
# Seeded srand with seed '20181028' from local date.
t/01-tidy.t .................. Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/5 subtests
```

**Comment by robrwo** [comment]
Hm, that is very strange.

**Comment by eserte** [comment]
`'run  -version'` --- this looks like the executable name is missing here.

**Comment by robrwo** [comment]
Ok, that means that it's not finding anything. Can you modify the test to output the value of Alien::TidyHTML5->bin_dir?

**Comment by robrwo** [comment]
(And then of course let me know if there's anything in that directory)

**Comment by plicease** [comment]
I think this is not quite right, the PkgConfig plugin should update these values so the gather section shouldn't be necessary.

https://github.com/robrwo/Alien-TidyHTML5/blob/master/alienfile#L37-L41

I can take a closer look at this later if it hasn't been resolved.

**Comment by eserte** [comment]
@robrwo : the output of bin_dir is undef:
```
$ /usr/perl5.24.2p/bin/perl -MAlien::TidyHTML5 -e 'warn Alien::TidyHTML5->bin_dir'
Warning: something's wrong at -e line 1.
```

**Comment by robrwo** [comment]
I'm also wondering if it's the -x test that is failing for some reason.

**Comment by robrwo** [comment]
@plicease That would be appreciated.

**Comment by plicease** [comment]
I think #3 should fix this.  Please see the notes in that PR for details.
